# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) can be set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html
puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name(role)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.add_role :admin


place = Place.find_or_create_by_name :name =>"Singapore Flyer",   :address =>  "30 Raffles Avenue #01-07 Singapore Flyer S039803", :description => "Singapore Flyer is the world's largest Giant Observation Wheel and is set to be one of Asia's biggest tourist attractions. It promises a panorama that captures Marina Bay’s skyline with a glimpse of neighbouring Malaysia and Indonesia.", :start_time => datetime.strptime("13/03/1902 08:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 22:00:00",'%y/%m/%d %h:%m:%s'),:category => "Outdoor" , :visit_time_minutes =>"30"
place = Place.find_or_create_by_name :name =>"Malay Heritage Centre",   :address =>  "85 Sultan Gate S198501", :description => "", :start_time => datetime.strptime("13/03/1902 08:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 18:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Singapore Cricket Club",   :address =>  "Connaught Drive S179681", :description => "This club is formed in 1852 for the British and European male elite.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 02:00:00",'%y/%m/%d %h:%m:%s'),:category => "Outdoor" , :visit_time_minutes =>"30"
place = Place.find_or_create_by_name :name =>"M.A.D (Mandarin Gallery)",   :address =>  "333A Orchard Road #03-01 Mandarin Gallery S238897", :description => "Located along orchard road at Mandarin Gallery, M.A.D (Museum of Art & Design) specializes in exhibiting painting and art pieces done by famous artist from around the world.", :start_time => datetime.strptime("30/12/1899 11:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 21:30:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Sentosa",   :address =>  "33 Allanbrooke Road S099981", :description => "Offering a variety of experiences for all ages, Sentosa is a must-visit destination for tourists and a popular recreational playground for local residents.", :start_time => datetime.strptime("30/12/1899 10:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 18:00:00",'%y/%m/%d %h:%m:%s'),:category => "Outdoor" , :visit_time_minutes =>"240"
place = Place.find_or_create_by_name :name =>"Heritage Wedding Gallery",   :address =>  "38 North Canal Road S059294", :description => "Heritage Wedding Gallery showcases Chinese wedding rituals and items commonly used in marriage ceremonies from ancient time to the modern days. This provides the audiences a better insight into the joyous occasion of the Chinese culture. Admission Fees: S$3.00 per person (Child under 12 will be complimentary)", :start_time => datetime.strptime("30/12/1899 11:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 18:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Singapore Zoo",   :address =>  "80 Mandai Lake Road Singapore Zoological Gardens S729826", :description => "The Singapore Zoo offers the opportunity to experience and be inspired by the wonders of nature. Home to over 2,500 specimens, the Zoo has attained a strong reputation internationally for its conservation initiatives and breeding programmes. It is also a designated rescued wildlife centre by the governing authority.", :start_time => datetime.strptime("30/12/1899 08:30:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 18:00:00",'%y/%m/%d %h:%m:%s'),:category => "Outdoor" , :visit_time_minutes =>"180"
place = Place.find_or_create_by_name :name =>"Sentosa Nature Discovery",   :address =>  "40 Imbiah Road S099700", :description => "The exploration starts with a fascinating gallery of interactive exhibits at the Gallery to brush up your science process skills: Observe, Classify, Compare and Infer. Equipped with these skills, step out into the jungle and explore a wilderness teeming with birds, insects, other wildlife and plants.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 17:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Civil Defence Heritage Gallery",   :address =>  "62 Hill Street Central Fire Station S179367", :description => "Civil Defence Heritage Gallery showcases the long history of civil defence and fire fighting developments in Singapore from the late 1800s to modern day. It also provides information on how to handle emergencies.", :start_time => datetime.strptime("30/12/1899 10:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 17:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Buddha Tooth Relic Temple & Museum",   :address =>  "288 South Bridge Road S058840", :description => "", :start_time => datetime.strptime("30/12/1899 07:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 19:00:00",'%y/%m/%d %h:%m:%s'),:category => "Religion" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Peranakan Museum",   :address =>  "39 Armenian Street S179941", :description => "The Peranakan Museum explores the culture of Peranakan communities in Southeast Asia. Installed in the former Tao Nan Chinese School, built in 1912, this intimate museum possesses one of the finest and most comprehensive collections of Peranakan objects.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 19:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Science Centre Singapore",   :address =>  "15 Science Centre Road S609081", :description => "", :start_time => datetime.strptime("30/12/1899 10:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 17:15:00",'%y/%m/%d %h:%m:%s'),:category => "Attractions" , :visit_time_minutes =>"90"
place = Place.find_or_create_by_name :name =>"Singapore Botanic Gardens",   :address =>  "1 Cluny Road Singapore Botanic Gardens S259569", :description => "Singapore Botanic Garden provides relaxing atmosphere that anyone will love located at Cluny Road.", :start_time => datetime.strptime("30/12/1899 05:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("31/12/1899 00:00:00",'%y/%m/%d %h:%m:%s'),:category => "Gardens " , :visit_time_minutes =>"120"
place = Place.find_or_create_by_name :name =>"Sungei Buloh Wetland Reserve",   :address =>  "301 Neo Tiew Crescent S718925", :description => "", :start_time => datetime.strptime("30/12/1899 07:30:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 19:00:00",'%y/%m/%d %h:%m:%s'),:category => "Nature" , :visit_time_minutes =>"120"
place = Place.find_or_create_by_name :name =>"Asian Civilisations Museum",   :address =>  "1 Empress Place S179555", :description => "The Asian Civilisations Museum (ACM) is the first museum in the region to present a broad yet integrated perspective of pan-Asian cultures and civilisations.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 19:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"90"
place = Place.find_or_create_by_name :name =>"Gardens By The Bay – Conservatories",   :address =>  "18 Marina Gardens Drive S018953", :description => "Gardens by the Bay comprises three waterfront gardens – Bay South, Bay East and Bay Central. Be amazed by a diversity of plant from around the world in the iconic cooled conservatories, be marveled by the Supertrees vertical garden, or discover the intricacies of plant life at the themed gardens.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 21:00:00",'%y/%m/%d %h:%m:%s'),:category => "Gardens " , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Gardens By The Bay -OCBC Skyway",   :address =>  "18 Marina Gardens Drive S018953", :description => "Gardens by the Bay comprises three waterfront gardens – Bay South, Bay East and Bay Central. Be amazed by a diversity of plant from around the world in the iconic cooled conservatories, be marveled by the Supertrees vertical garden, or discover the intricacies of plant life at the themed gardens.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 21:00:00",'%y/%m/%d %h:%m:%s'),:category => "Gardens " , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Gardens By The Bay - Outdoor Gardens",   :address =>  "18 Marina Gardens Drive S018953", :description => "Gardens by the Bay comprises three waterfront gardens – Bay South, Bay East and Bay Central. Be amazed by a diversity of plant from around the world in the iconic cooled conservatories, be marveled by the Supertrees vertical garden, or discover the intricacies of plant life at the themed gardens.", :start_time => datetime.strptime("30/12/1899 05:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 02:00:00",'%y/%m/%d %h:%m:%s'),:category => "Gardens " , :visit_time_minutes =>"90"
place = Place.find_or_create_by_name :name =>"National Museum of Singapore",   :address =>  "93 Stamford Road S178897", :description => "With a history dating back to its inception in 1887, the National Museum of Singapore is the nation’s oldest museum with a progressive mind.", :start_time => datetime.strptime("30/12/1899 10:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 18:00:00",'%y/%m/%d %h:%m:%s'),:category => "Museum" , :visit_time_minutes =>"90"
place = Place.find_or_create_by_name :name =>"Korean Cultural Center Singapore",   :address =>  "108 Robinson Road #11-01 / #12-01 Finexis Building S068900", :description => "Korean Cultural Center Singapore is the first Korean Cultural Center in Singapore which is a branch of the Konkuk University in Seoul, aimed at promoting the Korean culture int Singapore.", :start_time => datetime.strptime("30/12/1899 00:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 00:00:00",'%y/%m/%d %h:%m:%s'),:category => "Religion and cultural" , :visit_time_minutes =>"30"
place = Place.find_or_create_by_name :name =>"Memories at Old Fort Factory",   :address =>  "351 Upper Bukit Timah Road S588192", :description => "Memories at Old Fort Factory reflects the hardships faced by those who lived through the darkest years of Singapore's modern history have been captured befittingly at the old Ford Motor Factory, site of the British surrender now preserved by the National Archives of Singapore as a permanent exhibition gallery.", :start_time => datetime.strptime("30/12/1899 09:00:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 17:30:00",'%y/%m/%d %h:%m:%s'),:category => "Monuments/ Statues " , :visit_time_minutes =>"60"
place = Place.find_or_create_by_name :name =>"Night Safari",   :address =>  "80 Mandai Lake Road S729826", :description => "Night Safari is not any ordinary zoo illuminated by the night or a modern version of nocturnal houses found in many zoos world wide. Nestled in 40 hectares of lush secondary forest, the Night Safari offers guests the unique experience of exploring wildlife at night.", :start_time => datetime.strptime("30/12/1899 17:30:00",'%y/%m/%d %h:%m:%s'),  :end_time => datetime.strptime("30/12/1899 11:00:00",'%y/%m/%d %h:%m:%s'),:category => "Zoo" , :visit_time_minutes =>"120"